# datasource and jpa configuration
spring:
  datasource:
    url: jdbc:mysql://192.168.0.105:3306/TEST?characterEncoding=utf-8&useSSL=false
    username: root
    password: Tdh@123456
    driver-class-name: com.mysql.jdbc.Driver
  #JPA: Java Persistence Api
  jpa:
    database: mysql  #Specify th DBMS
    show-sql: true   #Show or not log for each sql query
    hibernate:       #Hibernate ddl auto(create, create-drop, update)
      ddl-auto: update