# datasource and jpa configuration
spring:
  datasource:
    jdbc-url: jdbc:mysql://47.107.49.211:3306/tempdb?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #JPA: Java Persistence Api
  jpa:
    database: mysql  #Specify th DBMS
    show-sql: true   #Show or not log for each sql query
    hibernate:       #Hibernate ddl auto(create, create-drop, update)
      ddl-auto: update

# mybatis指明映射类的包路径
mybatis:
  type-aliases-package: com.yuanjie.springboot.modules.mapper